backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "public/assets/blog"
public_folder: "/assets/blog"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }

  - name: "navigation"
    label: "Navigation"
    files:
      - label: "Navigation"
        name: "navigation"
        file: "src/_data/navigation.yml"
        fields:
          - label: "Navigation Items"
            name: "items"
            collapsed: false
            widget: "list"
            allow_add: false
            fields:
              - { label: "Text", name: "text", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "src/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Main Heading", name: "main_heading", widget: "string" }
          - {
              label: "Hero Description",
              name: "hero_description",
              widget: "string",
            }
          - {
              label: "Hero Button Text",
              name: "hero_button_text",
              widget: "string",
            }
          - {
              label: "Hero Button URL",
              name: "hero_button_url",
              widget: "string",
            }
          - { label: "Sub-Heading", name: "featured_title", widget: "string" }
      - label: "About"
        name: "about"
        file: "src/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Main Heading", name: "main_heading", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
